#!/bin/sh

# Bare-bones userspace initialization
export TERM="linux"
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
mount -t tmpfs tmpfs /tmp
hostname pinenote
ifconfig lo up

/etc/init.d/quill-init
